### PR TITLE
SDK switching support

### LINKED ISSUE #87: default linux install setup doesn't find SDK
**Describe the bug**
Fresh install flutter SDK on linux using snap, then setup coc-flutter showed `[lsp-server]: flutter SDK not found!`

**To Reproduce**
1. install flutter: https://flutter.dev/docs/get-started/install/linux#install-flutter-using-snapd
2. install coc-flutter
3. check output: `:CocCommand workspace.showOutput` then select flutter

**Expected behavior**
coc-flutter started without a problem

**Output**

```
[dev-command]: register dev command
[sdk]: which flutter command => /snap/bin/flutter
[sdk]: flutter command path => /usr/bin/snap
[sdk]: dart sdk home => /usr/bin/cache/dart-sdk
[sdk]: which dart command => /snap/bin/dart
[sdk]: dart command path => /usr/bin/snap
[sdk]: dart sdk home => /usr
[sdk]: analyzer path => /usr/bin/snapshots/analysis_server.dart.snapshot
[sdk]: dart command path => /usr/bin/dart
[sdk]: Dart SDK not found!
[sdk]: {
  "dartHome": "/usr",
  "analyzerSnapshotPath": "/usr/bin/snapshots/analysis_server.dart.snapshot"
}
[lsp-server]: flutter SDK not found!


```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Vim or Neovim: Neovim
 - (Neo)vim version: v0.4.4

I suppose this a Ubuntu specific problem, but I can't seem to find a good way to configure this

### LINKED ISSUE #90: Add an option to change the flutter sdk.
I use flutter version manager to change the version of flutter for different projects. It is possible to change the flutter sdk location in vs code easily. Is it possible to add the command like `flutter.changeSdk`. 

Below is the gif on how its changed in vscode.

Screen record from 2021-02-21 20 04 26

### LINKED ISSUE #96: Wrong flutter command path after updating
**Describe the bug**
I've installed `coc-flutter` on December and didn't update it until yesterday. I didn't modify any option regarding to executables or anything. As the title says, the flutter command path detected not correct, as shown in the logs later on
**To Reproduce**
My coc-settings.json flutter related lines:
```json
  "flutter.lsp.initialization.closingLabels": true,
  "flutter.lsp.debug": true,
  "flutter.trace.server": "verbose",
```
flutter --version
```
$ flutter --version
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (5 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5
```

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
Execute any flutter command (flutter pub get on save, :CocCommands flutter.devices..)

**Expected behavior**
I expect it to work as usual it did before, not specifying the path manually 
**Screenshots**
image
image

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Vim or Neovim: Neovim
 - (Neo)vim version: v0.4.4

**Output channel:**
```
[dev-command]: register dev command
[sdk]: which flutter command => /var/lib/snapd/snap/bin/flutter
[sdk]: flutter command path => /usr/bin/snap/bin/flutter
[sdk]: dart sdk home => /usr/bin/cache/dart-sdk
[sdk]: which dart command => /usr/bin/dart
[sdk]: dart command path => /opt/dart-sdk/bin/dart
[sdk]: dart sdk home => /opt/dart-sdk
[sdk]: analyzer path => /opt/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
[sdk]: dart command path => /opt/dart-sdk/bin/dart
[fs]: executing command /opt/dart-sdk/bin/dart --version
[sdk]: dart version: v2.10.4
[lsp-server]: rightVersion true
[global-commands]: pub get command, workspace: /home/username/project-path
[fs]: executing command /usr/bin/snap/bin/flutter pub get
[fs]: executing command /usr/bin/snap/bin/flutter emulators
[dev-command]: run dev server, devServer state: false
[server]: server start at: /home/username/project-path
```

### PR DESCRIPTION
**Pull request by Kavantix**
I added fvm support and an sdk selector list
When you select an sdk using the list it sets the `flutter.sdk.path` config option in the local config which is also used on startup. If that's not found it will try to use fvm if enabled(which is the default) and otherwise fallback on the old way.
So perhaps we should deprecate the `flutter-lookup` config option?

Restarting of the lsp server gave me some issues though (so it does not do that yet)
@iamcco It does not seem needed to restart the server in my testing since with doing the pub get the server will simply switch to the new flutter location so only any updates to the analysis snapshot itself will be missing, but do you perhaps know how to get the restart working?

Fixes #90
Fixes #87
Fixes #96

### CODE REVIEW

**Comment by Kavantix** [comment]
I also need to extract the find sdk logic and also use it on startup not just for the list

File: src/lib/sdk.ts [hunk 1]
```diff
@@ -99,36 +129,42 @@ class FlutterSDK {
...
+    } catch(error) {
+      log(`Error configuring sdk from searchPaths: ${error.message}}`);
+    }
+  }
 
-      if (flutterLookup.length == 0) {
-        flutterPath = (await which('flutter')).trim();
+  private async initDartSdkHomeFromLocalFvm() {
+    try {
+      if (await exists('./.fvm/flutter_sdk')) {
```
Comment (iamcco) [inline src/lib/sdk.ts:146]: It will has problem if current path is not the project root.

Comment (Kavantix) [reply src/lib/sdk.ts:146]: Hmm that’s true. Do we already have a way to find the project root ? I would guess it’s available through the workspace like the config?

File: src/lib/sdk.ts [hunk 2]
```diff
@@ -197,6 +233,130 @@ class FlutterSDK {
...
+
+    const lookupSdk = await this.sdkWithLookup(flutterLookup, currentSdk);
+    if (lookupSdk) {
+      sdks.push(lookupSdk);
+    }
+
+    const paths = config.get<string[]>('sdk.searchPaths', []);
+
+    for (let path of paths) {
+      path = path.replace('~', home).trim();
```
Comment (iamcco) [inline src/lib/sdk.ts:294]: use `/^~` should be better.

File: src/lib/sdk.ts [hunk 3]
```diff
@@ -197,6 +233,130 @@ class FlutterSDK {
...
+          isCurrent: location == currentSdk,
+        });
+      }
+    }
+
+    if (fvmEnabled) {
+      let fvmCachePath = join(home, 'fvm', 'versions');
+      const settingsPath = join(home, 'fvm', '.settings');
+      try {
+        const fvmSettingsFileExists = exists(settingsPath);
```
Comment (iamcco) [inline src/lib/sdk.ts:329]: missing await `await exists(settingsPath);`

File: src/server/lsp/index.ts [hunk 4]
```diff
@@ -33,12 +34,19 @@ export class LspServer extends Dispose {
     return this._client;
   }
 
-  async init() {
+  private lastId = 0;
+  private outchannel?: OutputChannel;
+
+  async init(): Promise<void> {
+    this.outchannel = workspace.createOutputChannel('flutter-lsp');
```
Comment (iamcco) [inline src/server/lsp/index.ts:41]: Should not recreate `workspace.createOutputChannel('flutter-lsp');` when restart, it will be better to separate the init and start lsp behavior

File: src/server/lsp/index.ts [hunk 5]
```diff
@@ -114,11 +121,13 @@ export class LspServer extends Dispose {
     };
 
     // Create the language client and start the client.
-    const client = new LanguageClient('flutter', 'flutter analysis server', serverOptions, clientOptions, isLspDebug);
+    const client = new LanguageClient(`flutter${this.lastId++}`, 'flutter analysis server', serverOptions, clientOptions, isLspDebug);
     this._client = client;
```
Comment (iamcco) [inline src/server/lsp/index.ts:125]: `this.lastId++` Is it necessary?

**Comment by iamcco** [comment]
sorry for the late response, so busy these days

>So perhaps we should deprecate the flutter-lookup config option?

Make sense

> Restarting of the lsp server gave me some issues though (so it does not do that yet)

what's the issue ?

> do you perhaps know how to get the restart working?

I think stop the old client and start a new one should work?

File: src/lib/sdk.ts (hunk 1 above)
Comment (iamcco) [reply src/lib/sdk.ts:146]: We can get workspace folder from `workspace.workspaceFolder`

**Comment by Kavantix** [comment]
> sorry for the late response, so busy these days

no worries!

> > So perhaps we should deprecate the flutter-lookup config option?
> 
> Make sense

Actually, considering how the asdf version manager works it might be nice to keep it around, it is now also used in the sdkslist


> > Restarting of the lsp server gave me some issues though (so it does not do that yet)
> 
> what's the issue ?
> 
> > do you perhaps know how to get the restart working?
> 
> I think stop the old client and start a new one should work?

So when stopping the client I could not get it to start again, adding the id worked though and it also closes the output channel when you stop it that’s why I added the other output channel.
If you have an idea for a better solution I’m all ears!

**Comment by iamcco** [comment]
Seems like some bug of coc.nvim. when toggle extension `enabled` to `disabeld` then `disabled` to `enabled`. the output channel become empty.

**Comment by Kavantix** [comment]
I changed the approach of restarting the client to stopping and starting again and having a class for the exec options so it can  change them dynamically.

**Comment by Kavantix** [comment]
Also added the snap searchpath and fixed the things you pointed out

File: src/lib/sdk.ts [hunk 6]
```diff
@@ -99,36 +135,43 @@ class FlutterSDK {
...
+    } catch(error) {
+      log(`Error configuring sdk from searchPaths: ${error.message}}`);
+    }
+  }
 
-      if (flutterLookup.length == 0) {
-        flutterPath = (await which('flutter')).trim();
+  private async initDartSdkHomeFromLocalFvm() {
+    try {
+      const fvmLocation = join(workspace.workspaceFolder.uri.replace(/^file:/, ''), '.fvm/flutter_sdk');
```
Comment (iamcco) [inline src/lib/sdk.ts:152]: We can use `Uri.parse(workspace.workspaceFolder.uri).fsPath` to get file system path. `Uri` import from coc.nvim.

**Comment by iamcco** [comment]
> Actually, considering how the asdf version manager works it might be nice to keep it around, it is now also used in the sdkslist

Seems like flutter-lookup no long use to init sdk

**Comment by Kavantix** [comment]
> > Actually, considering how the asdf version manager works it might be nice to keep it around, it is now also used in the sdkslist
> 
> Seems like flutter-lookup no longer use to init sdk

It is still used, inside the find function is also uses it so it also shows up in the list

**Comment by iamcco** [comment]
it looks good to me now. please let me know if it's ready to get merge.

**Comment by Kavantix** [comment]
Only thing left I think is updating the readme, we can do that in this PR or in a separate one.

**Comment by iamcco** [comment]
OK, let's merge first then add docs.
